### ISSUE TITLE
Saving only to localstorage?

### ISSUE THREAD

**Issue by Re4DeR** [Cybourgeoisie/cryptofolio#1]
Do you plan to save to another storage? Or I think just export/import should be great.

**Comment by Cybourgeoisie** [comment]
Yup - I started working on import / export, but I shifted gears to start working on a backend for permanent storage. I'll likely push import / export in the next few days to tide over the wait for a backend.

**Comment by Re4DeR** [comment]
Perfect! Thank you

**Comment by Cybourgeoisie** [comment]
You're welcome. I added import / export with the latest commit (dba3e3fcd4b8e63f6b32c871883dc1254ef7b37f). It's now live on http://10k.pizza (might need a force-refresh).

Let me know if you run into any issues. Thanks!

**Edit:** I might need to add a loading spinner for the larger import data sizes.

**Comment by Re4DeR** [comment]
Perfekt. Thanks!

**Comment by Re4DeR** [comment]
I was thinking and having no backend storage is one of the biggest benefit for me. Import/Export is absolutely perfect.

**Comment by Cybourgeoisie** [comment]
Thanks for your feedback! I've had a few requests for logins to use the same portfolio across multiple devices without import / export, but I'm going to make sure that the app continues to work 100% server-less. There might be a handful of features that require a backend (price alerts come to mind), but otherwise, the app should always be able to work without a server.
